"""add_category_product_mapping_to_banners

Revision ID: 54d6cd0bc560
Revises: 642f9e6d3f21
Create Date: 2025-11-18 22:07:11.911299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d6cd0bc560'
down_revision: Union[str, None] = '642f9e6d3f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('banners', sa.Column('product_id', sa.String(), nullable=True))
    op.create_foreign_key('banners_product_id_fkey', 'banners', 'products', ['product_id'], ['id'])
    op.create_foreign_key('banners_category_id_fkey', 'banners', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banners_category_id_fkey', 'banners', type_='foreignkey')
    op.drop_constraint('banners_product_id_fkey', 'banners', type_='foreignkey')
    op.drop_column('banners', 'product_id')
    op.drop_column('banners', 'category_id')
    # ### end Alembic commands ###
