"""add_icon_url_to_categories

Revision ID: e8affc695f6f
Revises: 7cc492186581
Create Date: 2025-11-15 21:02:55.122317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8affc695f6f'
down_revision: Union[str, None] = '7cc492186581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon_url')
    # ### end Alembic commands ###
